#!/usr/bin/env python

import sys
import requests
import json
import time
import pprint

endpoint = "http://localhost:8080/tasks/"

host = sys.argv[1]
action = sys.argv[2]
parms = sys.argv[3]

data_dict = {"node_id": host,
             "action": action,
             "payload": parms}

r = requests.post(endpoint, data=json.dumps(data_dict),
                  headers={'content-type': 'application/json'})

result = json.loads(r.text)
task_id = result['task']['id']

print "Added task as task id: %s" % task_id,

result = result['task']
while result['state'] == 'pending' or result['state'] == 'running':
    r = requests.get("%s%s" % (endpoint, task_id))
    result = json.loads(r.text)
    sys.stdout.write('.')
    sys.stdout.flush()
    time.sleep(1)

print "\n\n"
result = json.loads(result['result'])


pp = pprint.PrettyPrinter(indent=4)

print("Result code: %d" % result['result_code'])
print("Result msg:  %s" % result['result_str'])
print("Result data:")
pp.pprint(result['result_data'])
